config/routes.rb
Rails.application.routes.draw do
  resources :doctors do 
    collection do 
      get 'get_doc_list'
    end
  end

  root :to => 'doctors#index'

end

app/models/doctor.rb
class Doctor
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String 
	field :dob, type: Date
	field :race, type: String
	field :gender, type: String
	field :mobile_no, type: Integer
	field :city, type: String
	field :image_url, type: String

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    # @doctors = Doctor.all

    @city_name = Doctor.distinct(:city)
    @doc_name = Doctor.distinct(:name)
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_doc_list
    if params[:doc_name]
      @doc_info = Doctor.where(:name => params[:doc_name],:city => params[:city])

      respond_to do |format|
        format.json{render json: @doc_info}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.fetch(:doctor, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<div id="container">
  <div class="box">
    <div class="box-body">
        
      <div class="col-lg-12">
        <div class="col-lg-12">
          <h2 align="center">Search Doctor Based on City & Name</h2>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <select name="cities" id="cities_name" class="form-control">
            <option selected="selected" disabled>Select City</option>
            <% @city_name.each do |x| %>
              <option value="<%= x %>"><%= x %></option>
            <% end %>
          </select>
        </div>

        <div class="col-lg-4 col-md-4 col-sm-4">
          <input class="form-control" type="text" id="doc_name_auto" name="doc_name" placeholder="Enter Doctor Name">          
        </div>

        
        <div class="col-lg-4 col-md-4 col-sm-4">
          <button type="submit" id="doc_search_submit" class="btn btn-primary text-lg form-control"><span><b>Search</b></span></button>
        </div>
      </div>

      <div id="doc_result"></div>
    </div>
  </div>
</div>




<script>
  $('#doc_name_auto').typeahead({
    source: <%= raw(@doc_name) %> 
  });


  $('#doc_search_submit').on('click', function(){
    city_name = $('#cities_name :selected').text();
    doc_name = $('#doc_name_auto').val();

    if(doc_name.length <= 0 || city_name == 'Select City'){
      $('#doc_name_auto').focus();
    }else{
      $.ajax({
        type     : "GET",
        dataType : 'json',
        cache    : false,
        url      : '/doctors/get_doc_list?doc_name='+doc_name+'&city='+city_name,
        async    : false,
        success  : function(data) {
          $('#doc_result').empty();
          $.each(data, function (key,value) {
            var tbl = ''

            console.log(value);

            tbl+='<div class="row">'
              tbl+='<div class="col-lg-12 doc_list_box">'
                tbl+='<div class="col-lg-2">'
                  tbl+='<img src="'+value.image_url+'" height="100" width="100">'
                tbl+='</div>'
                tbl+='<div class="col-lg-10">'
                  tbl+='<div class="col-lg-2"><b>Doctor Name :</b></div>'
                  tbl+='<div class="col-lg-2">Dr. '+value.name+'</div>'
                  tbl+='<div class="col-lg-2"><b>Race :</b></div>'
                  tbl+='<div class="col-lg-2">'+value.race+'</div>'
                  tbl+='<div class="col-lg-2"><b>Gender :</b></div>'
                  tbl+='<div class="col-lg-2">'+value.gender+'</div>'
                tbl+='</div>'
                tbl+='<div class="col-lg-10">'
                  tbl+='<div class="col-lg-2"><b>DOB :</b></div>'
                  tbl+='<div class="col-lg-2">'+value.dob+'</div>'
                  tbl+='<div class="col-lg-2"><b>Mobile No. :</b></div>'
                  tbl+='<div class="col-lg-2">'+value.mobile_no+'</div>'
                  tbl+='<div class="col-lg-2"><b>City :</b></div>'
                  tbl+='<div class="col-lg-2">'+value.city+'</div>'
                tbl+='</div>'
              tbl+='</div>'
            tbl+='</div>'
            
            $('#doc_result').append(tbl);
          })
        }
      });
    }
  });
  
</script>

<style>
  .doc_list_box{
    padding: 25px;
  }
  #container{
    padding: 50px;
  }
</style>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DocSearchApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>